name: Link Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
